apiVersion: v1
kind: Service
metadata:
  name: {{ include "democrm.name" . }}-{{ .Values.service.name }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.app.name }}-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "democrm.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
